server:
  port: ${ORDER_PORT:8080}
spring:
  application:
    name: order
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
reserve-url: http://${WAREHOUSE_HOST:localhost}:${WAREHOUSE_PORT:8081}/warehouse/reserve
rollback-reserve-url: http://${WAREHOUSE_HOST:localhost}:${WAREHOUSE_PORT:8081}/warehouse/rollbackReserve
schedule-url: http://${DELIVERY_HOST:localhost}:${DELIVERY_PORT:8082}/delivery/schedule
cancel-shipment-url: http://${DELIVERY_HOST:localhost}:${DELIVERY_PORT:8082}/delivery/cancelShipment
make-payment-url: http://${BILLING_HOST:localhost}:${BILLING_PORT:8083}/billing/makePayment
