server:
  port: ${WAREHOUSE_PORT:8080}
spring:
  application:
    name: warehouse
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${USER_DB_HOST}:${USER_DB_PORT}/${USER_DB_NAME}
    username: ${USER_DB_USER}
    password: ${USER_DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: ${USER_DB_USER}
    password: ${USER_DB_PASSWORD}
    url: jdbc:postgresql://${USER_DB_HOST}:${USER_DB_PORT}/${USER_DB_NAME}
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
make-payment-url: http://${ORDER_SYS_BILLING_SERVICE_CHART_SERVICE_HOST:localhost}:8080/billing-service/makePayment
